### ISSUE TITLE
It doesn't download some boards.

### ISSUE THREAD

**Issue by MaybeGrimm** [Juraji/Pinterest-Downloader#1]
The downloader is heavenly, but for some reason it doesn't download the boards that have a - on the name.

**Comment by KedarBrooks** [comment]
This was the first downloaded to work for me, As @MaybeGrimm said, the down loader skips on some boards, I believe anything with a space or symbol will be skipped for some reason. Its not that big of an issue as changing the name of the board to have no spaces or symbols solves the problem.

**Comment by Juraji** [comment]
I'm going to archive this project, since it doesn't work with Pinterest anymore.

If you loved this, I created a new, more advanced app: https://github.com/Juraji/image-manager-2
It supports the current Pinterest layout (Since I used it just yesterday to sync up my backup :D)
It also has no issues whatsoever with special characters in board/section names
