### ISSUE TITLE
Feature Request: Download follower boards and other non followed boards.

### ISSUE THREAD

**Issue by ERasnier** [Juraji/Pinterest-Downloader#2]
Would love to copy and paste links to boards and click download as opposed to linking API token.
And you're a literal god for making this.

**Comment by Juraji** [comment]
Hey @ERasnier, sorry for the (somewhat VERY) late response!
I'm going to archive this project, since it doesn't work with Pinterest anymore.

If you loved this, I created a new, more advanced app: https://github.com/Juraji/image-manager-2
It supports the current Pinterest layout (Since I used it just yesterdayy to sync up my backup :D)
